### ISSUE TITLE
Add Bing support

### ISSUE THREAD

**Issue by micheleriva** [omnixent/omnixent#11]

**Comment by itsmegrave** [comment]
hey mate. May I work on this issue?

**Comment by micheleriva** [comment]
@itsmegrave sure! Take a look at this file to see how a service is implemented: https://github.com/omnixent/omnixent/blob/master/lib/services/google.ex

also, feel free to reach out if you have any question!

**Comment by TheJoin95** [comment]
I'll take this issue and I'm going to deliver the support with a PR.
I noticed that now you changed from Elixir to Typescript, am I correct?

**Comment by micheleriva** [comment]
@TheJoin95 yeah we're now backed by Deno. Seen your contribution and merged, thanks!
