### ISSUE TITLE
Documentation links

### ISSUE THREAD

**Issue by GreatGhostsss** [omnixent/omnixent#13]
Documentation links are broken.

**Comment by micheleriva** [comment]
Hey @GreatGhostsss ,
thank you so much for reaching out. We're currently working for making everything to work for the first stable release!

**Comment by micheleriva** [comment]
We're currently writing the documentation on @gitbookio, I'll share the link as soon as it is ready!

**Comment by micheleriva** [comment]
Hey @GreatGhostsss ,
we've put the project architecture online: https://architecture.omnixent.com, please note that we're currently writing it, therefore it is not really exhaustive yet.

We also published the first version for the REST API online here: https://docs.oss.omnixent.com.

have a nice day!

**Comment by GreatGhostsss** [comment]
This looks great, @micheleriva! I'd love to help in the future if I can 🙂
