### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by micheleriva** [omnixent/omnixent#4]
Yes, we need a proper logo. I've personally made the current one with Figma and I'm definitely not a graphic designer 😄

**Comment by IfeanyiEkperi** [comment]
Great. I'll love to work on this with you.

But I'll need more information to get started.

#I Care!

**Comment by micheleriva** [comment]
@IfeanyiEkperi that's awesome, thanks!
What kind information do you need? Feel free to ask here 😄

**Comment by IfeanyiEkperi** [comment]
Please could you share some ideas you may have (colours, shapes, etc) so I have something to start with.

I Care!

**Comment by micheleriva** [comment]
I'm currently using the following colors:

dark blue: #1A1057
light: #E7E3FF
accent: #FF10F5

but feel free to change them 😄 

Regarding shapes and other stuff, I'd like to keep the concept of "omniscience", "sight" and "knowledge"

**Comment by IfeanyiEkperi** [comment]
Okay. Noted.

I'll drop the samples soon.

**Comment by IfeanyiEkperi** [comment]
Hi @micheleriva sorry it took so long.

Here is the proposed logo for consideration.

**Comment by IfeanyiEkperi** [comment]
![20200811_141249](https://user-images.githubusercontent.com/6451526/89902041-da016000-dbdd-11ea-9676-111f21eabd17.jpg)

**Comment by IfeanyiEkperi** [comment]
![20200811_190845](https://user-images.githubusercontent.com/6451526/89932899-31b3c180-dc06-11ea-9ade-555a7d90f7a1.jpg)

Please review and advise.

**Comment by IfeanyiEkperi** [comment]
Hi @micheleriva, you didnt comment on the logo, if I need to add/remove something.
